services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: always

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    command:
      - "-config.file=/etc/promtail/promtail.yaml"
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/log/apache2:/var/log/apache2
      - /mnt/ssd/GeoLite2_db:/GeoLite2_db
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
