server:
  http_listen_port: 9080
  grpc_listen_port: 9096

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: 'modsec_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'modsec'
          __path__: /var/log/apache2/modsec_audit.log
