{
 "title": "Apache2 Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"apache_http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache2 Access Locations",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache_access\"} | pattern `<IP> - - [<datetime>] \"<method> <path> <protocol>\" <status> <size> \"<referrer>\" \"<useragent>\"` | line_format \"{{.IP}} {{.datetime}} {{.method}} {{.path}} {{.status}} {{.size}} {{.referrer}} {{.useragent}}\""
    }
   ]
  },
  {
   "title": "Apache2 Access Logs Simple",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache_access\"} | pattern `<IP> - - [<datetime>] \"<method> <path> <protocol>\" <status> <size> \"<referrer>\" \"<useragent>\"` | line_format \"{{.IP}} {{.datetime}} {{.method}} {{.path}} {{.status}} {{.size}} {{.referrer}} {{.useragent}}\""
    }
   ]
  },
  {
   "title": "Apache2 Suspicious Traffic",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"modsec\"} |~ \"ModSecurity: (Warning|Emergency|Alert|Critical)\""
    }
   ]
  },
  {
   "title": "Apache2 Access Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"apache_access\"}"
    }
   ]
  }
 ]
}