{
 "title": "RaspberryPi Monitoring",
 "tags": [ "linux" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }} temp"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "How much storage is used",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/etc/hostname\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{mountpoint=\"/etc/hostname\",fstype!=\"rootfs\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/etc/hostname\",fstype!=\"rootfs\"}) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Disk Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/etc/hostname\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/etc/hostname\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/etc/hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "SSD Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "How much storage is used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/ssd\", device=\"/dev/sda\"} - node_filesystem_avail_bytes{mountpoint=\"/mnt/ssd\", device=\"/dev/sda\"}) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/ssd\", device=\"/dev/sda\"}) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current R/W Data",
   "type": "gauge",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\", device=\"sda\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\", device=\"sda\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\", device=\"sda\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/ssd\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}