version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - APACHE_BODY_LIMIT=10737418240   # 10 GB
    ports:
      - 8080:80
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ${NEXTCLOUD_PATH}:/var/www/html
    networks:
      - nextcloud-net
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    restart: always

networks:
  nextcloud-net:
    driver: bridge
