services:
  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    volumes:
      - /var/log/apache2:/logs:ro
      - goaccess_data:/goaccess_data
      - /mnt/ssd/GeoLite2_db/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb:ro
    ports:
      - "7890:7890"
    command: >
      /logs/access.log
      --log-format=COMBINED
      --real-time-html
      --output=/goaccess_data/report.html
      --geoip-database=/usr/share/GeoIP/GeoLite2-City.mmdb
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: goaccess_nginx
    volumes:
      - goaccess_data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "7891:80"
    restart: unless-stopped

volumes:
  goaccess_data:
